name: CI

on:
  pull_request:
  push:
   branches:
     - main
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
          # It seems like dune 3.8 isn't available under opam-repository-mingw for Windows
          # disabling this for now

        ocaml-compiler:
          - 5.1.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage
